name: exchange_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  curl_logger_dio_interceptor: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_dotenv: null
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hex: ^0.2.0
  http: ^1.2.1
  logger: ^2.2.0
  pretty_dio_logger: ^1.3.1
  web3dart: ^2.7.3

dev_dependencies:
  analyzer: any
  build_runner: ^2.4.7
  copy_with_extension: ^5.0.2
  copy_with_extension_gen: ^5.0.4
  dart_code_metrics_presets: ^2.6.0

  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  import_sorter: ^4.6.0
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/abi/
    - .env
