// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DBdSWJR4XZATzzi7inUmtJtHuTXmq2M',
    appId: '1:447985532668:web:0b6930755903a86249e179',
    messagingSenderId: '447985532668',
    projectId: 'pixeldattask',
    authDomain: 'pixeldattask.firebaseapp.com',
    storageBucket: 'pixeldattask.appspot.com',
    measurementId: 'G-4F781SKJZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtF6xMVXbfcQ9j3hjhTT9s0e-tCS5VG1M',
    appId: '1:447985532668:android:31ff2269aa4ec8dc49e179',
    messagingSenderId: '447985532668',
    projectId: 'pixeldattask',
    storageBucket: 'pixeldattask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZkqKiKgp690ZXqO3HQzisYRycRNSeJgs',
    appId: '1:447985532668:ios:9edc866ae0dccca749e179',
    messagingSenderId: '447985532668',
    projectId: 'pixeldattask',
    storageBucket: 'pixeldattask.appspot.com',
    iosBundleId: 'com.example.exchangeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZkqKiKgp690ZXqO3HQzisYRycRNSeJgs',
    appId: '1:447985532668:ios:9edc866ae0dccca749e179',
    messagingSenderId: '447985532668',
    projectId: 'pixeldattask',
    storageBucket: 'pixeldattask.appspot.com',
    iosBundleId: 'com.example.exchangeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_DBdSWJR4XZATzzi7inUmtJtHuTXmq2M',
    appId: '1:447985532668:web:9d55f5f129f580f849e179',
    messagingSenderId: '447985532668',
    projectId: 'pixeldattask',
    authDomain: 'pixeldattask.firebaseapp.com',
    storageBucket: 'pixeldattask.appspot.com',
    measurementId: 'G-YH36SJXVEL',
  );
}
